jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # On crée un pare-feu uniquement pour le formulaire de login
        main_login:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu

        main:
            # Firewall qui prend en charge tout le site
            pattern: ^/
            # Autorise les utilisateurs anonymes
            anonymous: true
            # Méthode d'authentification
            form_login:
                # Route vers le formulaire de login
                login_path: login
                # Route vers la validation du formulaire
                check_path: login_check
            # Rend possible la déconnexion
            logout:
                # Route pour être déconnecté
                path: logout
                # Redirection après déconnexion
                target: /home





    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
